export const TRAIN_LINES = {
  "1": {
    id: "1",
    shortName: "1",
    longName: "Broadway - 7 Avenue Local",
    description: "Trains operate between 242 St in the Bronx and South Ferry in Manhattan, at all times",
    imgRef: '/train-line-icons/1.svg',
  },
  "2": {
    id: "2",
    shortName: "2",
    longName: "7 Avenue Express",
    description: "Trains operate between Wakefield-241 St, Bronx, and Flatbush Av-Brooklyn College, Brooklyn, at all times. Trains operate local in Bronx and Brooklyn. Trains operate express in Manhattan except late night when it operates local.",
    imgRef: '/train-line-icons/2.svg',
  },
  "3": {
    id: "3",
    shortName: "3",
    longName: "7 Avenue Express",
    description: "Trains operate between 148 St, 7 Av, Manhattan, and New Lots Av, Brooklyn, at all times except late nights. During late nights, trains operate only in Manhattan between 148 St, 7 Av and Times Square-42 St.",
    imgRef: '/train-line-icons/3.svg',
  },
  "4": {
    id: "4",
    shortName: "4",
    longName: "Lexington Avenue Express",
    description: "Trains operate daily between Woodlawn/Jerome Av, Bronx, and Utica Av/Eastern Pkwy, Brooklyn, running express in Manhattan and Brooklyn. During late night and early morning hours, trains run local in Manhattan and Brooklyn, and extend beyond Utica Av to New Lots/Livonia Avs, Brooklyn.",
    imgRef: '/train-line-icons/4.svg',
  },
  "5": {
    id: "5",
    shortName: "5",
    longName: "Lexington Avenue Express",
    description: "Weekdays daytime, most trains operate between either Dyre Av or 238 St-Nereid Av, Bronx, and Flatbush Av-Brooklyn College, Brooklyn. At all other times except during late nights, trains operate between Dyre Av, Bronx, and Bowling Green, Manhattan. During late nights trains operate only in the Bronx between Dyre Av and E 180 St/MorrisPark Av. Customers who ride during late night hours can transfer to 2 service at the E 180 St Station. At all times, trains operate express in Manhattan and Brooklyn. Weekdays, trains in the Bronx operate express from E 180 St to 149 St-3 Av during morning rush hours (from about 6 AM to 9 AM), and from 149 St-3 Av to E 180 St during the evening rush hours (from about 4 PM to 7 PM).",
    imgRef: '/train-line-icons/5.svg',
  },
  "6": {
    id: "6",
    shortName: "6",
    longName: "Lexington Avenue Local",
    description: "Local trains operate between Pelham Bay Park/Bruckner Expwy, Bronx, and Brooklyn Bridge/City Hall, Manhattan, at all times.",
    imgRef: '/train-line-icons/6.svg',
  },
  "7": {
    id: "7",
    shortName: "7",
    longName: "Flushing Local",
    description: "Trains operate between Main St-Flushing, Queens, and 34th-Hudson Yards, Manhattan, at all times.",
    imgRef: '/train-line-icons/7.svg',
  },
  "5X": {
    id: "5X",
    shortName: "5X",
    longName: "Lexington Avenue Express",
    description: "Weekdays daytime, most trains operate between either Dyre Av or 238 St-Nereid Av, Bronx, and Flatbush Av-Brooklyn College, Brooklyn. At all other times except during late nights, trains operate between Dyre Av, Bronx, and Bowling Green, Manhattan. During late nights trains operate only in the Bronx between Dyre Av and E 180 St/MorrisPark Av. Customers who ride during late night hours can transfer to 2 service at the E 180 St Station. At all times, trains operate express in Manhattan and Brooklyn. Weekdays, trains in the Bronx operate express from E 180 St to 149 St-3 Av during morning rush hours (from about 6 AM to 9 AM), and from 149 St-3 Av to E 180 St during the evening rush hours (from about 4 PM to 7 PM).",
    imgRef: '/train-line-icons/5d.svg',
  },
  "6X": {
    id: "6X",
    shortName: "6X",
    longName: "Pelham Bay Park Express",
    description: "Express trains operate between Pelham Bay Park/Bruckner Expwy, Bronx, and Brooklyn Bridge/City Hall, Manhattan, weekday mornings express in the Bronx toward Manhattan. Weekday afternoons and evenings, these trains operate express in the Bronx toward Pelham Bay Park.",
    imgRef: '/train-line-icons/6d.svg',
  },
  "7X": {
    id: "7X",
    shortName: "7X",
    longName: "Flushing Express",
    description: "Trains operate between Main St-Flushing, Queens, and 34th St-Hudson Yards, Manhattan, weekday mornings toward Manhattan. Weekday afternoons and evenings, these trains operate express to Queens.",
    imgRef: '/train-line-icons/7d.svg',
  },
  "A": {
    id: "A",
    shortName: "A",
    longName: "8 Avenue Express",
    description: "Trains operate between Inwood-207 St, Manhattan and Far Rockaway-Mott Avenue, Queens at all times. Also from about 6 AM until about midnight, additional trains operate between Inwood-207 St and Lefferts Boulevard (trains typically alternate between Lefferts Blvd and Far Rockaway). During weekday morning rush hours, special trains operate from Rockaway Park-Beach 116 St, Queens, toward Manhattan. These trains make local stops between Rockaway Park and Broad Channel. Similarly, in the evening rush hour special trains leave Manhattan operating toward Rockaway Park-Beach 116 St, Queens.",
    imgRef: '/train-line-icons/a.svg',
  },
  "B": {
    id: "B",
    shortName: "B",
    longName: "6 Avenue Express",
    description: "Trains operate, weekdays only, between 145 St, Manhattan, and Brighton Beach, Brooklyn at all times except late nights. The route extends to Bedford Park Blvd, Bronx, during rush hours.",
    imgRef: '/train-line-icons/b.svg',
  },
  "C": {
    id: "C",
    shortName: "C",
    longName: "8 Avenue Local",
    description: "Trains operate between 168 St, Manhattan, and Euclid Av, Brooklyn, daily from about 6 AM to 11 PM.",
    imgRef: '/train-line-icons/c.svg',
  },
  "D": {
    id: "D",
    shortName: "D",
    longName: "6 Avenue Express",
    description: "Trains operate, at all times, from 205 Street, Bronx, to Stillwell Avenue, Brooklyn via Central Park West and 6th Avenue in Manhattan, and via the Manhattan Bridge to and from Brooklyn. When in Brooklyn trains operate via 4th Avenue then through Bensonhurst to Coney Island. Trains typically operate local in the Bronx, express in Manhattan, and local in Brooklyn. But please note that Bronx rush hour trains operate express (peak direction ONLY), and Brooklyn trains operate express along the 4th Avenue segment (all times except late nights).",
    imgRef: '/train-line-icons/d.svg',
  },
  "E": {
    id: "E",
    shortName: "E",
    longName: "8 Avenue Local",
    description: "Trains operate between Jamaica Center (Parsons/Archer), Queens, and World Trade Center, Manhattan, at all times. E trains operate express in Queens at all times except late nights when they operate local.",
    imgRef: '/train-line-icons/e.svg',
  },
  "F": {
    id: "F",
    shortName: "F",
    longName: "Queens Blvd Express/ 6 Av Local",
    description: "Trains operate at all times between Jamaica-179 St, Queens, and Stillwell Av, Brooklyn via the 63 St Connector (serving 21 St-Queensbridge, Roosevelt Island, Lexington Av-63 St, and 57 St-6 Av). F trains operate local in Manhattan and express in Queens at all times.",
    imgRef: '/train-line-icons/f.svg',
  },
  "FS": {
    id: "FS",
    shortName: "S",
    longName: "Franklin Avenue Shuttle",
    description: "Train provides full time connecting service between the A and C at the Franklin Av/Fulton St station, and the Q at the Prospect Park/Empire Blvd station. A free transfer is also available at the Botanic Garden/Eastern Parkway Station to the 2, 3, 4, and 5 service.",
    imgRef: '/train-line-icons/sf.svg',
  },
  "FX": {
    id: "FX",
    shortName: "FX",
    longName: "Brooklyn F Express",
    description: "Trains operate rush hour only between Jamaica-179 St, Queens, and Stillwell Av, Brooklyn, weekday mornings toward Manhattan, weekday afternoons toward Coney Island. These trains operate express in Brooklyn between Church Av and Jay St-MetroTech for two trips each rush hour period.",
    imgRef: '/train-line-icons/fd.svg',
  },
  "G": {
    id: "G",
    shortName: "G",
    longName: "Brooklyn-Queens Crosstown",
    description: "Trains operate between Court Square, Queens and Church Av, Brooklyn on weekdays, late nights, and weekends.",
    imgRef: '/train-line-icons/g.svg',
  },
  "GS": {
    id: "GS",
    shortName: "S",
    longName: "42 St Shuttle",
    description: "Operates in Manhattan between Grand Central and Times Square. The shuttle provides a free transfer between 4, 5, 6, and 7 service at Grand Central-42 St and A, C, E, N, Q, R, W, 1, 2, 3, and 7 service at Times Square-42 St. The shuttle runs at all times except during late nights, from about 12 midnight to 6 AM.",
    imgRef: '/train-line-icons/sg.svg',
  },
  "H": {
    id: "H",
    shortName: "S",
    longName: "Rockaway Park Shuttle",
    description: "Service operates at all times between Broad Channel, and Rockaway Park, Queens.",
    imgRef: '/train-line-icons/s.svg',
  },
  "J": {
    id: "J",
    shortName: "J",
    longName: "Nassau St Local",
    description: "Trains operate weekdays between Jamaica Center (Parsons/Archer), Queens, and Broad St, Manhattan at all times. During weekdays, Trains going to Manhattan run express in Brooklyn between Myrtle Av and Marcy Av from about 7 AM to 1 PM and from Manhattan from 1:30 PM and 8 PM. During weekday rush hours, trains provide skip-stop service. Skip-stop service means that some stations are served by J trains, some stations are served by the Z trains, and some stations are served by both J and Z trains. J/Z skip-stop service runs towards Manhattan from about 7 AM to 8:15 AM and from Manhattan from about 4:30 PM to 5:45 PM.",
    imgRef: '/train-line-icons/j.svg',
  },
  "L": {
    id: "L",
    shortName: "L",
    longName: "14 St-Canarsie Local",
    description: "Trains operate between 8 Av/14 St, Manhattan, and Rockaway Pkwy/Canarsie, Brooklyn, at all times.",
    imgRef: '/train-line-icons/l.svg',
  },
  "M": {
    id: "M",
    shortName: "M",
    longName: "Queens Blvd Local/6 Av Local",
    description: "Trains operate between Middle Village-Metropolitan Avenue, Queens and Myrtle Avenue, Brooklyn at all times. Service is extended weekdays (except late nights) Continental Ave, Queens, All trains provide local service.",
    imgRef: '/train-line-icons/m.svg',
  },
  "N": {
    id: "N",
    shortName: "N",
    longName: "Broadway Local",
    description: "Trains operate from Astoria-Ditmars Boulevard, Queens, to Stillwell Avenue, Brooklyn, at all times. N trains in Manhattan operate along Broadway and across the Manhattan Bridge to and from Brooklyn. Trains in Brooklyn operate along 4th Avenue, then through Borough Park and Gravesend. Trains typically operate local in Queens and express in Manhattan and Brooklyn. Late night trains operate local in Manhattan and to/from Brooklyn via Whitehall St, Manhattan. Weekends N trains operate local in Manhattan.",
    imgRef: '/train-line-icons/n.svg',
  },
  "Q": {
    id: "Q",
    shortName: "Q",
    longName: "Broadway Express",
    description: "Trains operate between 96 St-2 Av, Manhattan, and Stillwell Av, Brooklyn at all times. Trains operate local in Brooklyn at all times. Train operate express in Manhattan at all times, except late nights when trains operate local in Manhattan.",
    imgRef: '/train-line-icons/q.svg',
  },
  "R": {
    id: "R",
    shortName: "R",
    longName: "Broadway Local",
    description: "Trains operate local between Forest Hills-71 Av, Queens, and 95 St/4 Av, Brooklyn, at all times except late nights. During late nights, trains operate between Whitehall St-South Ferry, Manhattan and 95 St/4 Av, Brooklyn",
    imgRef: '/train-line-icons/r.svg',
  },
  "SI": {
    id: "SI",
    shortName: "SIR",
    longName: "Staten Island Railway",
    description: "Service runs 24 hours a day between the St George and Tottenville terminals. At the St George terminal, customers can make connections with Staten Island Ferry service to Manhattan.",
    imgRef: '/train-line-icons/sir.svg',
  },
  "W": {
    id: "W",
    shortName: "W",
    longName: "Broadway Local",
    description: "Trains operate from Astoria-Ditmars Boulevard, Queens, to Whitehall St, Manhattan, on weekdays only.",
    imgRef: '/train-line-icons/w.svg',
  },
  "Z": {
    id: "Z",
    shortName: "Z",
    longName: "Nassau St Express",
    description: "Trains operate weekday rush hours only. During weekday rush hours, J and Z trains provide skip-stop service. Skip-stop service means that some stations are served by J trains, some stations are served by the Z trains, and some stations are served by both J and Z trains. J/Z skip-stop service runs towards Manhattan from about 7 AM to 8:15 AM and from Manhattan from about 4:30 PM to 5:45 PM.",
    imgRef: '/train-line-icons/z.svg',
  }
}

export const BASE_URL = process.env.VITE_BASE_URL;
